(setq flymake-max-parallel-syntax-checks 8)
(setq flymake-run-in-place nil)
(setq temporary-file-directory "~/.emacs.d/tmp/")
(setq flymake-number-of-errors-to-display 4)
(provide 'init-flymake)
